import type { ResourceKind } from "./types";

/**
 * Canonical origin for the deployed site. Override at build time with
 * NEXT_PUBLIC_SITE_URL (e.g. a custom domain) — falls back to the Netlify URL.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://mcp-skills-hub.netlify.app"
).replace(/\/+$/, "");

export const SITE_NAME = "AI Library";

/** Build an absolute URL from a site-relative path. */
export function absoluteUrl(path = "/") {
  return new URL(path, SITE_URL).toString();
}

/**
 * Shared social-share image (generated by app/opengraph-image.tsx).
 * Include this in any page that defines its own `openGraph`, otherwise the
 * inherited file-convention image is dropped when the object is overridden.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "AI Library — Skills, MCP servers & GitHub repos for every AI assistant",
};

/** Catalog metadata keyed by resource kind — labels, paths, breadcrumbs. */
export const KIND_META: Record<
  ResourceKind,
  { label: string; singular: string; path: string }
> = {
  skills: { label: "Skills", singular: "Skill", path: "/skills" },
  mcps: { label: "MCP Servers", singular: "MCP Server", path: "/mcps" },
  repos: { label: "Repos", singular: "Repo", path: "/repos" },
};

/** Detail-route path for a resource, e.g. /skills/pdf-processing */
export function resourcePath(kind: ResourceKind, slug: string) {
  return `${KIND_META[kind].path}/${slug}`;
}

type Crumb = { name: string; path: string };

/** Build a schema.org BreadcrumbList from Home down to the given trail. */
export function breadcrumbJsonLd(trail: Crumb[]) {
  const items = [{ name: SITE_NAME, path: "/" }, ...trail];
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.name,
      item: absoluteUrl(c.path),
    })),
  };
}

/** Build a schema.org CollectionPage for a catalog listing. */
export function collectionJsonLd(kind: ResourceKind, description: string) {
  const { label, path } = KIND_META[kind];
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "@id": `${SITE_URL}${path}#collection`,
    name: `${label} — ${SITE_NAME}`,
    description,
    url: absoluteUrl(path),
    isPartOf: { "@id": `${SITE_URL}/#website` },
  };
}
