import type { ResourceKind } from "./types";

/**
 * Canonical origin for the deployed site.
 *
 * Hardcoded rather than left to an env var: the default previously pointed at
 * Netlify, so after the move to Vercel every canonical, og:url, sitemap entry
 * and robots directive on the live site named a domain serving a stale build.
 * A canonical is a directive, so that actively told Google to index the dead
 * copy instead of this one. The correct value belongs in the repo where it
 * can't silently drift from where the site actually is.
 *
 * NEXT_PUBLIC_SITE_URL still overrides it, for a custom domain or previews.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://mcp-skills-hub.vercel.app"
).replace(/\/+$/, "");

export const SITE_NAME = "AI Library";

/** Build an absolute URL from a site-relative path. */
export function absoluteUrl(path = "/") {
  return new URL(path, SITE_URL).toString();
}

/**
 * Shared social-share image (generated by app/opengraph-image.tsx).
 * Include this in any page that defines its own `openGraph`, otherwise the
 * inherited file-convention image is dropped when the object is overridden.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "AI Library — Skills, MCP servers & GitHub repos for every AI assistant",
};

/** Catalog metadata keyed by resource kind — labels, paths, breadcrumbs. */
export const KIND_META: Record<
  ResourceKind,
  { label: string; singular: string; path: string }
> = {
  skills: { label: "Skills", singular: "Skill", path: "/skills" },
  mcps: { label: "MCP Servers", singular: "MCP Server", path: "/mcps" },
  repos: { label: "Repos", singular: "Repo", path: "/repos" },
};

/**
 * URL-safe form of a category name. Categories are real route segments rather
 * than query params so each one is an independently indexable page with its
 * own canonical — a `?category=` variant would just be collapsed into the
 * bare catalog URL by the canonical tag.
 */
export function categorySlug(name: string) {
  return name.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

/** Category-route path, e.g. /mcps/category/databases-and-storage */
export function categoryPath(kind: ResourceKind, name: string) {
  return `${KIND_META[kind].path}/category/${categorySlug(name)}`;
}

/** Detail-route path for a resource, e.g. /skills/pdf-processing */
export function resourcePath(kind: ResourceKind, slug: string) {
  return `${KIND_META[kind].path}/${slug}`;
}

type Crumb = { name: string; path: string };

/** Build a schema.org BreadcrumbList from Home down to the given trail. */
export function breadcrumbJsonLd(trail: Crumb[]) {
  const items = [{ name: SITE_NAME, path: "/" }, ...trail];
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.name,
      item: absoluteUrl(c.path),
    })),
  };
}

/** Build a schema.org CollectionPage for a catalog listing. */
export function collectionJsonLd(kind: ResourceKind, description: string) {
  const { label, path } = KIND_META[kind];
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "@id": `${SITE_URL}${path}#collection`,
    name: `${label} — ${SITE_NAME}`,
    description,
    url: absoluteUrl(path),
    isPartOf: { "@id": `${SITE_URL}/#website` },
  };
}
